// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJnqbxiv4n-9JsdbHD-aaZQ7O6qBjPxmA',
    appId: '1:281744297831:web:7b6e6481a976495a3569c2',
    messagingSenderId: '281744297831',
    projectId: 'notiforyou-flutter-project',
    authDomain: 'notiforyou-flutter-project.firebaseapp.com',
    storageBucket: 'notiforyou-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAmxvizeTkgcPI8FdBnv3k-6tBBJz4O-0',
    appId: '1:281744297831:android:6324f6a91ce03e5e3569c2',
    messagingSenderId: '281744297831',
    projectId: 'notiforyou-flutter-project',
    storageBucket: 'notiforyou-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBn2cBjba2za7Oj0ey21J2vcrFyExzJVk',
    appId: '1:281744297831:ios:7250308b8b535d5a3569c2',
    messagingSenderId: '281744297831',
    projectId: 'notiforyou-flutter-project',
    storageBucket: 'notiforyou-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.notiforyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBn2cBjba2za7Oj0ey21J2vcrFyExzJVk',
    appId: '1:281744297831:ios:7250308b8b535d5a3569c2',
    messagingSenderId: '281744297831',
    projectId: 'notiforyou-flutter-project',
    storageBucket: 'notiforyou-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.notiforyou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJnqbxiv4n-9JsdbHD-aaZQ7O6qBjPxmA',
    appId: '1:281744297831:web:3df19574e15b155a3569c2',
    messagingSenderId: '281744297831',
    projectId: 'notiforyou-flutter-project',
    authDomain: 'notiforyou-flutter-project.firebaseapp.com',
    storageBucket: 'notiforyou-flutter-project.firebasestorage.app',
  );
}
